[package]
name = "telnet-chat"
version = "0.1.0"
authors = ["Alice Ryhl <alice@ryhl.io>"]
edition = "2018"

[dependencies]
tokio = { version = "1.1.0", features = ["full"] }
tokio-util = { version = "0.6.2", features = ["codec"] }
futures = "0.3.12"
bytes = "1.0.1"
