[package]
name = "telnet-chat"
version = "0.1.0"
authors = ["Alice Ryhl <alice@ryhl.io>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2.21", features = ["full"] }
tokio-util = { version = "0.3.1", features = ["codec"] }
futures = "0.3.5"
bytes = "0.5.4"
